server:
  port: 8080
  servlet:
    context-path: /study

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 6000

setting:
  user:
    age: 12
    name: xyq
    address: 湖南邵阳
  label-id-list:
    - 1
    - 2
    - 3